version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: springboot-postgres
    environment:
      POSTGRES_DB: cloudstarter
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demopass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: